"""core: access_requests (onboarding)

Revision ID: 20bd73051734
Revises: aa8e8d09df3c
Create Date: 2026-08-13 01:03:43.849324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20bd73051734'
down_revision: Union[str, None] = 'aa8e8d09df3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('empresa_nombre', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'aprobado', 'rechazado', name='access_request_status'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_access_requests_email'), 'access_requests', ['email'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_access_requests_email'), table_name='access_requests', schema='core')
    op.drop_table('access_requests', schema='core')
    op.execute("DROP TYPE IF EXISTS access_request_status")
    # ### end Alembic commands ###
