"""scanner: documentos

Revision ID: 3270c83ef3e4
Revises: e4e7567bc793
Create Date: 2026-08-13 09:00:02.157580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3270c83ef3e4'
down_revision: Union[str, None] = 'e4e7567bc793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS scanner")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('tipo_etiqueta', sa.String(length=100), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('campos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scanner'
    )
    op.create_index(op.f('ix_scanner_documentos_company_id'), 'documentos', ['company_id'], unique=False, schema='scanner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanner_documentos_company_id'), table_name='documentos', schema='scanner')
    op.drop_table('documentos', schema='scanner')
    # ### end Alembic commands ###
