"""sire: credenciales y columnas de archivo del job

Revision ID: 56e52af717b0
Revises: 255311d7996f
Create Date: 2026-08-12 00:02:42.435333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '56e52af717b0'
down_revision: Union[str, None] = '255311d7996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('usuario_sol', sa.String(length=50), nullable=False),
    sa.Column('clave_sol_enc', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret_enc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    schema='sire'
    )
    op.add_column('reconciliation_jobs', sa.Column('empresa_filename', sa.String(length=255), nullable=True), schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('empresa_file_path', sa.String(length=500), nullable=True), schema='sire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_jobs', 'empresa_file_path', schema='sire')
    op.drop_column('reconciliation_jobs', 'empresa_filename', schema='sire')
    op.drop_table('company_credentials', schema='sire')
    # ### end Alembic commands ###
