"""sire: extra_tickets del job

Revision ID: 5d8c64a0c28b
Revises: db58136b2c1c
Create Date: 2026-08-12 22:54:07.254513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d8c64a0c28b'
down_revision: Union[str, None] = 'db58136b2c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_jobs', sa.Column('extra_tickets', sa.JSON(), nullable=True), schema='sire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_jobs', 'extra_tickets', schema='sire')
    # ### end Alembic commands ###
