"""core inicial

Revision ID: a0fdbed25649
Revises: 
Create Date: 2026-08-11 23:37:45.197047
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'a0fdbed25649'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', name='company_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_companies_ruc'), 'companies', ['ruc'], unique=True, schema='core')
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_modules_key'), 'modules', ['key'], unique=True, schema='core')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_permissions_key'), 'permissions', ['key'], unique=True, schema='core')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('platform', 'company', name='role_scope'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_roles_key'), 'roles', ['key'], unique=True, schema='core')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_sub', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', 'pendiente', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_auth0_sub'), 'users', ['auth0_sub'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_table('company_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('activo', 'suspendido', name='company_module_status'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_company_modules_company_id'), 'company_modules', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_company_modules_module_key'), 'company_modules', ['module_key'], unique=False, schema='core')
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', name='membership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_membership_user_company'),
    schema='core'
    )
    op.create_index(op.f('ix_core_memberships_company_id'), 'memberships', ['company_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_memberships_role_id'), 'memberships', ['role_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_memberships_user_id'), 'memberships', ['user_id'], unique=False, schema='core')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions', schema='core')
    op.drop_index(op.f('ix_core_memberships_user_id'), table_name='memberships', schema='core')
    op.drop_index(op.f('ix_core_memberships_role_id'), table_name='memberships', schema='core')
    op.drop_index(op.f('ix_core_memberships_company_id'), table_name='memberships', schema='core')
    op.drop_table('memberships', schema='core')
    op.drop_index(op.f('ix_core_company_modules_module_key'), table_name='company_modules', schema='core')
    op.drop_index(op.f('ix_core_company_modules_company_id'), table_name='company_modules', schema='core')
    op.drop_table('company_modules', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_auth0_sub'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_core_roles_key'), table_name='roles', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_index(op.f('ix_core_permissions_key'), table_name='permissions', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_index(op.f('ix_core_modules_key'), table_name='modules', schema='core')
    op.drop_table('modules', schema='core')
    op.drop_index(op.f('ix_core_companies_ruc'), table_name='companies', schema='core')
    op.drop_table('companies', schema='core')
    # ### end Alembic commands ###
    for tipo in (
        "membership_status",
        "company_module_status",
        "user_status",
        "role_scope",
        "company_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
