"""sire: reutilizar_propuesta del job

Revision ID: aa8e8d09df3c
Revises: 5d8c64a0c28b
Create Date: 2026-08-12 23:22:10.548224
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa8e8d09df3c'
down_revision: Union[str, None] = '5d8c64a0c28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_jobs', sa.Column('reutilizar_propuesta', sa.Boolean(), nullable=False, server_default='false'), schema='sire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_jobs', 'reutilizar_propuesta', schema='sire')
    # ### end Alembic commands ###
