"""sire: report_files y contadores por escenario

Revision ID: d0b1c2b483d0
Revises: 56e52af717b0
Create Date: 2026-08-12 00:17:45.404511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0b1c2b483d0'
down_revision: Union[str, None] = '56e52af717b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('csv_a_storage_path', sa.String(length=500), nullable=True),
    sa.Column('csv_a_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('csv_b_storage_path', sa.String(length=500), nullable=True),
    sa.Column('csv_b_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('csv_c_storage_path', sa.String(length=500), nullable=True),
    sa.Column('csv_c_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('csv_d_storage_path', sa.String(length=500), nullable=True),
    sa.Column('csv_d_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['sire.reconciliation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    schema='sire'
    )
    op.add_column('reconciliation_results', sa.Column('escenario_a_count', sa.Integer(), nullable=False, server_default='0'), schema='sire')
    op.add_column('reconciliation_results', sa.Column('escenario_b_count', sa.Integer(), nullable=False, server_default='0'), schema='sire')
    op.add_column('reconciliation_results', sa.Column('escenario_c_count', sa.Integer(), nullable=False, server_default='0'), schema='sire')
    op.add_column('reconciliation_results', sa.Column('escenario_d_count', sa.Integer(), nullable=False, server_default='0'), schema='sire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_results', 'escenario_d_count', schema='sire')
    op.drop_column('reconciliation_results', 'escenario_c_count', schema='sire')
    op.drop_column('reconciliation_results', 'escenario_b_count', schema='sire')
    op.drop_column('reconciliation_results', 'escenario_a_count', schema='sire')
    op.drop_table('report_files', schema='sire')
    # ### end Alembic commands ###
