"""sire: mapeo de columnas guardado y campos avanzados del job

Revision ID: db58136b2c1c
Revises: d0b1c2b483d0
Create Date: 2026-08-12 00:35:44.669766
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db58136b2c1c'
down_revision: Union[str, None] = 'd0b1c2b483d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_file_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tipo_libro', sa.String(length=10), nullable=False),
    sa.Column('delimiter', sa.String(length=5), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('has_header', sa.Boolean(), nullable=False),
    sa.Column('skip_rows', sa.Integer(), nullable=False),
    sa.Column('columnas', sa.JSON(), nullable=True),
    sa.Column('serie_numero_combinado', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'tipo_libro', name='uq_file_mapping_company_libro'),
    schema='sire'
    )
    op.create_index(op.f('ix_sire_company_file_mappings_company_id'), 'company_file_mappings', ['company_id'], unique=False, schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('sin_sire', sa.Boolean(), nullable=False, server_default='false'), schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('mapeo_config', sa.JSON(), nullable=True), schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('cobertura_fechas', sa.JSON(), nullable=True), schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('num_ticket', sa.String(length=30), nullable=True), schema='sire')
    op.add_column('reconciliation_jobs', sa.Column('propuesta_origen_at', sa.DateTime(timezone=True), nullable=True), schema='sire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_jobs', 'propuesta_origen_at', schema='sire')
    op.drop_column('reconciliation_jobs', 'num_ticket', schema='sire')
    op.drop_column('reconciliation_jobs', 'cobertura_fechas', schema='sire')
    op.drop_column('reconciliation_jobs', 'mapeo_config', schema='sire')
    op.drop_column('reconciliation_jobs', 'sin_sire', schema='sire')
    op.drop_index(op.f('ix_sire_company_file_mappings_company_id'), table_name='company_file_mappings', schema='sire')
    op.drop_table('company_file_mappings', schema='sire')
    # ### end Alembic commands ###
