"""sunat: credenciales, drive_tokens y job_results

Revision ID: e4e7567bc793
Revises: 20bd73051734
Create Date: 2026-08-13 01:33:41.348878
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4e7567bc793'
down_revision: Union[str, None] = '20bd73051734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS sunat")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    schema='sunat'
    )
    op.create_table('job_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('resultados', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sunat'
    )
    op.create_index(op.f('ix_sunat_job_results_company_id'), 'job_results', ['company_id'], unique=False, schema='sunat')
    op.create_index(op.f('ix_sunat_job_results_job_id'), 'job_results', ['job_id'], unique=True, schema='sunat')
    op.create_table('sunat_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('usuario_enc', sa.Text(), nullable=False),
    sa.Column('clave_enc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    schema='sunat'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sunat_credentials', schema='sunat')
    op.drop_index(op.f('ix_sunat_job_results_job_id'), table_name='job_results', schema='sunat')
    op.drop_index(op.f('ix_sunat_job_results_company_id'), table_name='job_results', schema='sunat')
    op.drop_table('job_results', schema='sunat')
    op.drop_table('drive_tokens', schema='sunat')
    # ### end Alembic commands ###
