CAMPOS_POR_TIPO: dict[str, dict[str, str]] = {
    "factura_electronica": {
        "ruc_proveedor":      "RUC Proveedor",
        "razon_social_prov":  "Razón Social Proveedor",
        "direccion_prov":     "Dirección Proveedor",
        "ruc_cliente":        "RUC Cliente",
        "razon_social_cli":   "Razón Social Cliente",
        "direccion_cli":      "Dirección Cliente",
        "fecha_emision":      "Fecha de Emisión",
        "fecha_vencimiento":  "Fecha de Vencimiento",
        "condicion_pago":     "Condición de Pago",
        "serie":              "Serie",
        "numero_doc":         "Número",
        "moneda":             "Moneda",
        "descripcion":        "Descripción",
        "subtotal":           "Subtotal / Op. Gravada",
        "descuentos":         "Descuentos",
        "igv":                "IGV (18%)",
        "otros_cargos":       "Otros Cargos",
        "total":              "Total",
    },
    "boleta_venta": {
        "ruc_proveedor":     "RUC Emisor",
        "razon_social_prov": "Razón Social Emisor",
        "nombre_cliente":    "Nombre Cliente",
        "ruc_cliente":       "RUC Cliente (opcional)",
        "fecha_emision":     "Fecha de Emisión",
        "serie":             "Serie",
        "numero_doc":        "Número",
        "moneda":            "Moneda",
        "descripcion":       "Descripción",
        "subtotal":          "Subtotal",
        "igv":               "IGV",
        "total":             "Total",
    },
    "recibo_honorarios": {
        "ruc_emisor":           "RUC Emisor",
        "nombre_emisor":        "Nombre Emisor",
        "dni_emisor":           "DNI Emisor",
        "nombre_cliente":       "Nombre Cliente / Empresa",
        "ruc_cliente":          "RUC Cliente",
        "fecha_emision":        "Fecha de Emisión",
        "periodo_servicio":     "Período del Servicio",
        "serie":                "Serie",
        "numero_doc":           "Número",
        "moneda":               "Moneda",
        "descripcion_servicio": "Descripción del Servicio",
        "monto_honorarios":     "Monto de Honorarios",
        "retencion_pct":        "% Retención",
        "retencion_monto":      "Monto Retención (4%)",
        "neto_pagar":           "Neto a Pagar",
    },
    "nota_credito": {
        "ruc_proveedor":     "RUC Proveedor",
        "razon_social_prov": "Razón Social Proveedor",
        "ruc_cliente":       "RUC Cliente",
        "razon_social_cli":  "Razón Social Cliente",
        "fecha_emision":     "Fecha de Emisión",
        "serie":             "Serie",
        "numero_doc":        "Número",
        "moneda":            "Moneda",
        "descripcion":       "Descripción",
        "doc_ref_tipo":      "Tipo Doc. Referencia",
        "doc_ref_serie":     "Serie Doc. Referencia",
        "doc_ref_numero":    "N° Doc. Referencia",
        "motivo":            "Motivo",
        "monto_afectado":    "Monto Afectado",
        "igv":               "IGV",
        "total":             "Total",
    },
    "nota_debito": {
        "ruc_proveedor":     "RUC Proveedor",
        "razon_social_prov": "Razón Social Proveedor",
        "ruc_cliente":       "RUC Cliente",
        "razon_social_cli":  "Razón Social Cliente",
        "fecha_emision":     "Fecha de Emisión",
        "serie":             "Serie",
        "numero_doc":        "Número",
        "moneda":            "Moneda",
        "descripcion":       "Descripción",
        "doc_ref_tipo":      "Tipo Doc. Referencia",
        "doc_ref_serie":     "Serie Doc. Referencia",
        "doc_ref_numero":    "N° Doc. Referencia",
        "motivo":            "Motivo",
        "monto_afectado":    "Monto Afectado",
        "igv":               "IGV",
        "total":             "Total",
    },
    "recibo_luz": {
        "empresa":              "Empresa",
        "ruc_empresa":          "RUC Empresa",
        "nombre_cliente":       "Nombre Cliente",
        "numero_suministro":    "N° Suministro",
        "direccion_suministro": "Dirección Suministro",
        "tarifa":               "Tarifa",
        "periodo":              "Período",
        "mes":                  "Mes",
        "anio":                 "Año",
        "fecha_emision":        "Fecha Emisión",
        "fecha_vencimiento":    "Fecha Vencimiento",
        "lectura_anterior":     "Lectura Anterior",
        "lectura_actual":       "Lectura Actual",
        "consumo_kwh":          "Consumo (kWh)",
        "cargo_fijo":           "Cargo Fijo",
        "energia_activa":       "Energía Activa",
        "alumbrado_publico":    "Alumbrado Público",
        "igv":                  "IGV",
        "deuda_anterior":       "Deuda Anterior",
        "total_pagar":          "Total a Pagar",
    },
    "recibo_agua": {
        "empresa":           "Empresa (EPS)",
        "ruc_empresa":       "RUC Empresa",
        "nombre_cliente":    "Nombre Cliente",
        "numero_cuenta":     "N° Cuenta",
        "direccion":         "Dirección",
        "categoria":         "Categoría",
        "periodo":           "Período",
        "fecha_emision":     "Fecha Emisión",
        "fecha_vencimiento": "Fecha Vencimiento",
        "consumo_m3":        "Consumo (m³)",
        "cargo_fijo":        "Cargo Fijo",
        "agua_potable":      "Agua Potable",
        "alcantarillado":    "Alcantarillado",
        "igv":               "IGV",
        "deuda_anterior":    "Deuda Anterior",
        "total_pagar":       "Total a Pagar",
    },
    "recibo_gas": {
        "empresa":           "Empresa",
        "ruc_empresa":       "RUC Empresa",
        "nombre_cliente":    "Nombre Cliente",
        "numero_contrato":   "N° Contrato",
        "numero_medidor":    "N° Medidor",
        "periodo":           "Período",
        "fecha_emision":     "Fecha Emisión",
        "fecha_vencimiento": "Fecha Vencimiento",
        "lectura_anterior":  "Lectura Anterior",
        "lectura_actual":    "Lectura Actual",
        "consumo_m3":        "Consumo (m³)",
        "cargo_fijo":        "Cargo Fijo",
        "cargo_variable":    "Cargo Variable",
        "igv":               "IGV",
        "total_pagar":       "Total a Pagar",
    },
    "recibo_telefonia": {
        "empresa":           "Operadora",
        "ruc_empresa":       "RUC Empresa",
        "nombre_cliente":    "Nombre Cliente",
        "numero_cuenta":     "N° Cuenta",
        "numero_linea":      "N° Línea / Teléfono",
        "plan":              "Plan Tarifario",
        "tipo_servicio":     "Tipo de Servicio",
        "periodo":           "Período",
        "fecha_emision":     "Fecha Emisión",
        "fecha_vencimiento": "Fecha Vencimiento",
        "cargos_fijos":      "Cargos Fijos",
        "cargos_variables":  "Cargos Variables",
        "roaming":           "Roaming",
        "descuentos":        "Descuentos",
        "igv":               "IGV",
        "total_pagar":       "Total a Pagar",
    },
    "asistencia": {
        "trabajador":     "Trabajador",
        "dni":            "DNI",
        "cargo":          "Cargo",
        "departamento":   "Departamento",
        "fecha":          "Fecha",
        "hora_entrada":   "Hora de Entrada",
        "hora_salida":    "Hora de Salida",
        "turno":          "Turno",
        "horas_normales": "Horas Normales",
        "horas_extras":   "Horas Extras",
        "firma_presente": "¿Asistió?",
    },
    "boleta_pago": {
        "empresa":         "Empresa",
        "ruc_empresa":     "RUC Empresa",
        "periodo":         "Período (Mes)",
        "trabajador":      "Trabajador",
        "dni":             "DNI",
        "cargo":           "Cargo",
        "codigo":          "Código",
        "fecha_ingreso":   "Fecha de Ingreso",
        "dias_trabajados": "Días Trabajados",
        "asegurado_afp":   "AFP / Asegurado en",
        "basico":          "Básico Mensual",
        "total_ingresos":  "Total Ingresos",
        "total_descuento": "Total Descuentos",
        "total_aporte":    "Total Aportes (Empleador)",
        "neto_pagar":      "Neto a Pagar",
    },
}


def campos_de(tipo: str) -> dict[str, str]:
    return CAMPOS_POR_TIPO.get(tipo, {})
